AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'docs/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'config.ru'
Metrics/LineLength:
  Max: 99
Style/Documentation:
  Enabled: false
