# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

decks = [];
10.times do |i|
  decks.push(Deck.create(name: "Personality Adjectives ##{i + 1}"))
end
cards = [
  ['Anxious', 'experiencing worry, unease, or nervousness, typically about an imminent event or something with an uncertain outcome'],
  ['Naughty', 'disobedient; badly behaved'],
  ['Stubborn', 'Having or showing dogged determination not to change one\'s attitude or position on something, esp. in spite of good arguments or reasons to do so'],
  ['Sensitive', 'Easily damaged, injured, or distressed by slight changes'],
  ['Intelligent','having or showing intelligence, especially of a high level.'],
  ['Emotional', 'Having feelings that are easily excited and openly displayed'],
  ['Bad-tempered', 'easily annoyed or made angry'],
  ['Nervous', 'Easily agitated or alarmed; tending to be anxious; highly strung'],
  ['Mean', 'Unwilling to give or share things, esp. money; not generous. Unkind, spiteful, or unfair.'],
  ['Distracted', 'Unable to concentrate because one\'s mind is preoccupied'],
  ['Dishonest', 'Behaving or prone to behave in an untrustworthy or fraudulent way'],
  ['Rude', 'Offensively impolite or ill-mannered. Ignorant and uneducated'],
  ['Discreet', 'Careful and circumspect in one\'s speech or actions, esp. in order to avoid causing offense or to gain an advantage. Intentionally unobtrusive'],
  ['Cheeky', 'impudent or irreverent, typically in an endearing or amusing way.'],
  ['Cheerful', 'noticeably happy and optimistic'],
  ['Energetic', 'showing or involving great activity or vitality.'],
  ['Untidy', 'not arranged neatly and in order.'],
  ['Pessimistic', 'tending to see the worst aspect of things or believe that the worst will happen'],
  ['Optimistic', 'hopeful and confident about the future.'],
  ['Unpleasant', 'causing discomfort, unhappiness, or revulsion; disagreeable.'],
  ['Talkative', 'fond of or given to talking.'],
  ['Calm', 'not showing or feeling nervousness, anger, or other emotions.'],
  ['Passionate', 'showing or caused by strong feelings or a strong belief.'],
  ['Proud', 'feeling deep pleasure or satisfaction as a result of one\'s own achievements, qualities, or possessions or those of someone with whom one is closely associated.'],
  ['Sincere', 'free from pretense or deceit; proceeding from genuine feelings'],
  ['Lively', 'full of life and energy; active and outgoing.'],
  ['Silly', 'having or showing a lack of common sense or judgment; absurd and foolish.'],
  ['Shy', 'being reserved or having or showing nervousness or timidity in the company of other people.'],
  ['Determined', 'having made a firm decision and being resolved not to change it.'],
  ['Versatile', 'able to adapt or be adapted to many different functions or activities.'],
  ['Sociable', 'willing to talk and engage in activities with other people; friendly.'],
  ['Worried', 'anxious or troubled about actual or potential problems.'],
  ['Thoughtful', 'absorbed in or involving thought.'],
  ['Humble', 'having or showing a modest or low estimate of one\'s own importance.'],
  ['Frank', 'open, honest, and direct in speech or writing, especially when dealing with unpalatable matters.'],
  ['Obedient', 'complying or willing to comply with orders or requests; submissive to another\'s will.'],
  ['Honest', 'free of deceit and untruthfulness; sincere.'],
  ['Fearless', 'lacking fear'],
  ['Generous', 'showing a readiness to give more of something, as money or time, than is strictly necessary or expected.'],
  ['Compassionate', 'feeling or showing sympathy and concern for others.'],
  ['Warm-hearted', 'sympathetic and kind'],
  ['Disobedient', 'refusing to obey rules or someone in authority.'],
  ['Straightforward', 'uncomplicated and easy to do or understand'],
  ['Selfish', 'lacking consideration for others; concerned chiefly with one\'s own personal profit or pleasure'],
  ['Imaginative', 'having or showing creativity or inventiveness'],
  ['Placid', 'not easily upset or excited'],
  ['Jealous', 'feeling or showing envy of someone or their achievements and advantages.'],
  ['Enthusiastic', 'having or showing intense and eager enjoyment, interest, or approval.'],
  ['Persistent', 'continuing firmly or obstinately in a course of action in spite of difficulty or opposition.'],
  ['Sensible', 'Possessing or displaying prudence'],
  ['Rational', 'Able to think clearly, sensibly, and logically'],
  ['Reserved', 'Slow to reveal emotion or opinions'],
  ['Self-confident', 'trusting in one\'s abilities, qualities, and judgment.'],
  ['Bossy', 'fond of giving people orders; domineering.'],
  ['Plucky', 'Having or showing determined courage in the face of difficulties'],
  ['Patient', 'able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious'],
  ['Impatient', 'having or showing a tendency to be quickly irritated or provoked'],
  ['Easygoing', 'relaxed and tolerant in approach or manner.'],
  ['Careless', 'not giving sufficient attention or thought to avoiding harm or errors.'],
  ['Messy', 'untidy or dirty'],
  ['Hard-working', 'tending to work with energy and commitment; diligent.'],
  ['Creative', 'relating to or involving the imagination or original ideas, especially in the production of an artistic work.'],
  ['Broad-minded', 'tolerant or liberal in one\'s views and reactions; not easily offended.'],
  ['Faithful', 'loyal, constant, and steadfast.'],
  ['Courageous', 'not deterred by danger or pain; brave.'],
  ['Loyal', 'giving or showing firm and constant support or allegiance to a person or institution.'],
  ['Modest', 'unassuming or moderate in the estimation of one\'s abilities or achievements'],
  ['Tidy', 'arranged neatly and in order.'],
  ['Confident', 'feeling or showing confidence in oneself; self-assured.'],
  ['Attentive', 'paying close attention to something.'],
  ['Loving', 'feeling or showing love or great care.'],
  ['Reliable', 'consistently good in quality or performance; able to be trusted.'],
  ['Scared', 'fearful; frightened.'],
  ['Conscientious', 'wishing to do what is right, especially to do one\'s work or duty well and thoroughly.'],
  ['Careful', 'making sure of avoiding potential danger, mishap, or harm; cautious.'],
  ['Gentle', 'mild in temperament or behavior; kind or tender'],
  ['Neat', 'Habitually tidy, well groomed, or well organized'],
  ['Dynamic', 'Positive in attitude and full of energy and new ideas'],
  ['Fair-minded', 'impartial in judgment; just'],
  ['Impartial', 'treating all rivals or disputants equally; fair and just'],
  ['Supportive', 'Providing encouragement or emotional help'],
  ['Timid', 'showing a lack of courage or confidence; easily frightened.'],
  ['Brave', 'ready to face and endure danger or pain; showing courage.'],
  ['Ambitious', 'having or showing a strong desire and determination to succeed.'],
  ['Polite', 'having or showing behavior that is respectful and considerate of other people.'],
  ['Courteous', 'polite, respectful, or considerate in manner'],
  ['Humorous', 'causing lighthearted laughter and amusement; comic'],
  ['Popular', 'liked, admired, or enjoyed by many people or by a particular person or group'],
  ['Hypocritical', 'behaving in a way that suggests one has higher standards or more noble beliefs than is the case.'],
  ['Adventurous', 'willing to take risks or to try out new methods, ideas, or experiences.']
];
cards.each_with_index do |(term, definition), ind|
  Card.create(term: term.downcase, definition: definition, deck: decks[ind % 10])
end
